/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    war
    `maven-publish`
    id("org.gretty") version "3.1.1"
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://mavensync.zkoss.org/maven2")
    }

    maven {
        url = uri("https://mavensync.zkoss.org/eval")
    }

}

dependencies {
    implementation("org.zkoss.zk:zkmax:9.6.3-Eval")
    implementation("com.theokanning.openai-gpt3-java:client:0.9.0")
}

group = "org.zkoss.support"
version = "1.0-SNAPSHOT"
description = "The ai-chartroom Project"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
